-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- =============================================================================

-- Hyprland config — aesarbil · ThinkPad X260

-- =============================================================================

package.loaded["matugen-colors"] = nil
local matugen_colors = require("matugen-colors")

--###############

--## MONITORS ###

--###############

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

--##################

--## MY PROGRAMS ###

local terminal = "kitty"

local fileManager = "nautilus"

local menu = "rofi -show drun"

--################

--## AUTOSTART ###

--################




--exec-once = dunst

--nuevas notificaciones



--exec-once = hyprpaper








--############################

--## ENVIRONMENT VARIABLES ###

--############################

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("GDK_BACKEND", "wayland")

hl.env("GTK_THEME", "catppuccin-macchiato-blue-standard")

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

--####################

--## LOOK AND FEEL ###

--####################

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
        border_size = 2,
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = matugen_colors.active_border,
            inactive_border = matugen_colors.inactive_border,
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        shadow = {
            enabled = true,
            range = 8,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 5,
            passes = 2,
            vibrancy = 0.1696,
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("easeOutQuint", {
    type = "bezier",
    points = { { 0.23, 1 }, { 0.32, 1 } },
})
hl.curve("easeInOutCubic", {
    type = "bezier",
    points = { { 0.65, 0.05 }, { 0.36, 1 } },
})
hl.curve("linear", {
    type = "bezier",
    points = { { 0, 0 }, { 1, 1 } },
})
hl.curve("almostLinear", {
    type = "bezier",
    points = { { 0.5, 0.5 }, { 0.75, 1 } },
})
hl.curve("quick", {
    type = "bezier",
    points = { { 0.15, 0 }, { 0.1, 1 } },
})
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

hl.config({
    dwindle = {
        --pseudotile     = true
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        --vfr                     = true
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
})

--############

--## INPUT ###

--############

hl.config({
    input = {
        kb_layout = "es",
        kb_variant = "nodeadkeys",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true,
            scroll_factor = 0.4,
            clickfinger_behavior = true,
        },
    },
})

--##################

--## KEYBINDINGS ###

--##################

local mainMod = "SUPER"

-- --- Aplicaciones ---

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("pgrep rofi && pkill rofi || rofi -show drun"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("zen"))

--bind = $mainMod, D,     exec, pgrep waypaper && pkill waypaper || waypaper

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("pgrep rofi && pkill rofi || bash ~/.config/rofi/wallpaper-picker.sh"))

-- --- Gestión de ventanas ---

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "F11", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- --- Foco ---

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- --- Mover ventanas ---

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))

-- --- Redimensionar ---

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- --- Workspaces ---

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- --- Mover ventana a workspace ---

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- --- Scratchpad ---

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- --- Scroll entre workspaces ---

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- --- Ratón ---

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- --- Sistema ---

hl.bind(mainMod .. " + " .. "K", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("pgrep wleave && pkill wleave || wleave"))

-- --- Portapapeles ---

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))

-- --- Capturas ---

hl.bind("Print", hl.dsp.exec_cmd("grim -o \"$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name')\" - | tee ~/Imágenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy && notify-send \"📸 Monitor actual copiado y guardado\""))

hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grim - | tee ~/Imágenes/capturas/screenshot-$(date +%Y%m%d-%H%M%S).png | wl-copy && notify-send \"📸 Todas las pantallas copiado y guardado\""))

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy && notify-send \"📋 Selección copiada\""))

-- --- Multimedia ---

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && pamixer --get-volume >/tmp/wobpipe"), { repeating = true, locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && pamixer --get-volume >/tmp/wobpipe"), { repeating = true, locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true, locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+ && brightnessctl -m | cut -d, -f4 | tr -d '%' >/tmp/wobpipe"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%- && brightnessctl -m | cut -d, -f4 | tr -d '%' >/tmp/wobpipe"), { repeating = true, locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

hl.window_rule({
    name  = "nofocus-empty",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        fullscreen = 0,
    },
})

hl.window_rule({
    name  = "pavucontrol-float",
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
    size = { 900, 600 },
})

hl.window_rule({
    name  = "nm-float",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    name  = "blueman-float",
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    name  = "preferencias-float",
    match = {
        title = "^(Preferencias)$",
    },
    float = true,
})

hl.window_rule({
    name  = "ajustes-float",
    match = {
        title = "^(Ajustes)$",
    },
    float = true,
})

hl.window_rule({
    name  = "karere-immediate",
    match = {
        class = "^(io\\.github\\.tobagin\\.karere)$",
    },
    immediate = true,
})

hl.window_rule({
    name  = "waypaper-float",
    match = {
        class = "^(waypaper)$",
    },
    float = true,
    center = true,
    size = { 900, 600 },
})

hl.layer_rule({
    match = {
        namespace = "^(swaync-control-center|swaync-notification-window)$",
    },
    blur = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = {
        namespace = "^(wleave)$",
    },
    blur = true,
    ignore_alpha = 0.3,
})

hl.window_rule({
    name  = "swaync-transparent",
    match = {
        class = "^(swaync)$",
    },
    opacity = "0.85 0.85",
})

hl.window_rule({
    name  = "mullvad-nodecoration",
    match = {
        class = "^(Mullvad Browser)$",
    },
    decorate = false,
})

--##################

--## DEVICE RULES ###

--##################

hl.device({
    name = "synaptics-tm3075-002",
    sensitivity = 0,
    natural_scroll = true,
    tap_to_click = true,
    disable_while_typing = true,
    scroll_factor = 0.4,
    clickfinger_behavior = true,
})

hl.device({
    name = "tpps/2-ibm-trackpoint",
    sensitivity = -0.5,
    scroll_factor = 0.3,
})

hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wleave --service")
    hl.exec_cmd("Telegram -startintray")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("rm -f /tmp/wobpipe && mkfifo /tmp/wobpipe && tail -f /tmp/wobpipe | wob")
end)
